name: panopticon
environment:
  sdk: ^3.7.0
dependencies:
  pool: ^1.5.1
  http: ^1.3.0
  sqlite3: ^2.7.5
  yaml: ^3.1.3
  pub_semver: ^2.2.0
  pub:
    git: https://github.com/dart-lang/pub
  pana:
    git: https://github.com/dart-lang/pana
  console: ^4.1.0
  crypto: ^3.0.6
  convert: ^3.1.2
  collection: ^1.19.1
  typed_data: ^1.4.0
  ffi: ^2.1.4
dev_dependencies:
  ffigen: ^18.1.0

ffigen:
  output: 'lib/generated_bindings.dart'
  headers:
    entry-points:
      - '/usr/include/openssl/sha.h'